version: 0.2

phases: 
    install: 
        runtime-versions:
            nodejs: latest
        commands: 
            - echo "installing something"
    pre_build:
        commands:
            - echo "we are in the pre build phase"
    build: 
        commands: 
            - echo "we are in build block"
            - echo "we will run some tests"
            - grep -Fp "Congrats" index.html
    post_build:
        commands:
            - echo "we are in post build"
